# Write your MySQL query statement below
SELECT E1.EMPLOYEE_ID, E1.NAME, COUNT(*) REPORTS_COUNT, ROUND(AVG(E2.AGE)) AVERAGE_AGE
FROM EMPLOYEES E1
JOIN EMPLOYEES E2 ON E1.EMPLOYEE_ID = E2.REPORTS_TO
GROUP BY EMPLOYEE_ID
ORDER BY EMPLOYEE_ID