WITH DAILY_AMOUNT AS (
    SELECT VISITED_ON, SUM(AMOUNT) AS DAILY_SUM
    FROM CUSTOMER
    GROUP BY VISITED_ON
)
SELECT 
    A.VISITED_ON,
    SUM(B.DAILY_SUM) AS AMOUNT,
    ROUND(AVG(B.DAILY_SUM), 2) AS AVERAGE_AMOUNT
FROM 
    DAILY_AMOUNT A
JOIN 
    DAILY_AMOUNT B 
    ON B.VISITED_ON BETWEEN DATE_SUB(A.VISITED_ON, INTERVAL 6 DAY) AND A.VISITED_ON
GROUP BY 
    A.VISITED_ON
HAVING 
    COUNT(B.VISITED_ON) = 7;
