# Write your MySQL query statement below
SELECT S.USER_ID, 
    CASE WHEN C.ACTION IS NOT NULL THEN ROUND(SUM(C.ACTION = 'CONFIRMED') / COUNT(C.ACTION), 2) 
    ELSE 0
    END AS CONFIRMATION_RATE
FROM SIGNUPS S
LEFT JOIN CONFIRMATIONS C ON S.USER_ID = C.USER_ID
GROUP BY S.USER_ID 
